#!/bin/bash
# Automated Bash scrtip to manage user id in  in IDRAC 7 & 8 
#Script written by Altaf Hussain (Linux Server Admin) Ibm
#list of servers to be staged in /home/user's_home_folder/server.list
#List of passwords to be staged in /home/user's_home_folder/passwords1
#list of servers which had issues will be logged under /tmp/pending
#Logs can be found under /tmp/logs
#final status can be found under /tmp/output 

a=/tmp/input
d=/tmp/logs
f=/tmp/output

id=username
pass=password

filecontent=( `cat  "/home/user/server.list"` )
count=${#filecontent[@]}

for (( i = 0 ; i < count ; i++ ))
do
echo " `date`                     "$id" ">>$d
NEWPASS=""
	while [ `echo $NEWPASS|wc -c` -lt 5 ] ;do
		NEWPASS=`mkpasswd -l 12 -s 0|grep -vE "0|O|l|1| "|grep -v "'"|grep -v '"'`
	done
sshpass -p $pass ssh -q -t -o StrictHostKeyChecking=no $id@${filecontent[$i]} "racadm getsvctag"  >>$f

	if [ $? -eq 0 ]
	then 
echo "============================================="  >>$f
			  sshpass -p $pass ssh -q -t -o StrictHostKeyChecking=no $id@${filecontent[$i]} "racadm getconfig -u root" >$a
		m=`grep Index $a |cut -d'=' -f2|tr -d '\r'`
		if [ -z $m ]; then
echo " User root not found on the blade ${filecontent[$i]} "
		else

sshpass -p $pass ssh -q -t -o StrictHostKeyChecking=no $id@${filecontent[$i]} "racadm config -g cfgUserAdmin -o cfgUserAdminPassword -i $m '$NEWPASS' " >>$d
		echo " Password has been modified for the user root on ${filecontent[$i]} $NEWPASS" >> $f

fi
echo "=============================================" >>$f


		echo " password modification  has been successfully completed on ${filecontent[$i]}" >> $d
	else 
		echo "Not able to connect to ${filecontent[$i]}" >> $d
fi
done
