#!/bin/bash
# Automated Bash scrtip to reset root password HP servers 
#Script written by Altaf Hussain (Linux Server Admin) Ibm
#list of servers to be staged in /home/user's_home_folder/server.list
#list of servers which had issues will be logged under /tmp/pending
#Logs can be found under /tmp/logs
#final status can be found under /tmp/output 

a=/tmp/input
d=/tmp/logs
f=/tmp/output

id=username
pass='password'

filecontent=( `cat  "~/server.list"` )
count=${#filecontent[@]}

for (( i = 0 ; i < count ; i++ ))
do
echo " `date`                     "$id" ">>$d
NEWPASS=""
	while [ `echo $NEWPASS|wc -c` -lt 5 ] ;do
		NEWPASS=`mkpasswd -l 12 -s 0|grep -vE "0|O|l|1| "|grep -v "'"|grep -v '"'`
	done
sshpass -p $pass ssh -q -t -o StrictHostKeyChecking=no $id@${filecontent[$i]} "uptime"  >>$f

	if [ $? -eq 0 ]
	then 
echo "============================================="  >>$f
			  sshpass -p $pass ssh -q -t -o StrictHostKeyChecking=no $id@${filecontent[$i]} "ipmitool list user |grep testuser" >$a
		m=`grep Administrator $a |cut -d' ' -f4|tr -d '\r'`
		if [ -z $m ]; then
echo " User root not found on the blade ${filecontent[$i]} "
		else

echo ('$pass')|sshpass -p $pass ssh -q -t -o StrictHostKeyChecking=no $id@${filecontent[$i]} "sudo /usr/bin/ipmitool user set password 12 " >>$d
		echo " Password has been modified for the user root on ${filecontent[$i]} $NEWPASS" >> $f

fi
echo "=============================================" >>$f


		echo " password modification  has been successfully completed on ${filecontent[$i]}" >> $d
	else 
		echo "Not able to connect to ${filecontent[$i]}" >> $d
fi
done

